framework:
    assets:
        packages:
            app:
                json_manifest_path: '%kernel.project_dir%/public/build/app/manifest.json'
            back:
                json_manifest_path: '%kernel.project_dir%/public/build/back/manifest.json'
