controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

admin:
    resource: ../../src/Controller/Back/
    type: annotation
    prefix: /admin
